apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis 
  labels:
    app: redis 

spec:
  selector:
    matchLabels:
      app: redis 
  template:
    metadata:
      labels:
        app: redis 
    spec:
      containers:
      - name: server 
        image: redis 
        
        command: ["redis-server", "--save 10 1"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
